# Generated by Django 4.2.20 on 2025-05-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("video", "Video")],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("maths", "Mathematics"),
                            ("english", "English"),
                            ("physics", "Physics"),
                            ("chemistry", "Chemistry"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="pdf_files/"),
                ),
                ("video_link", models.URLField(blank=True, null=True)),
                ("description", models.TextField()),
                ("keywords", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("material_types", models.ManyToManyField(to="material.materialtype")),
            ],
        ),
    ]
